services:
  db:
    container_name: "database-flight-application"
    image: postgres:17-alpine3.21
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - flight-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - flight-network

volumes:
  postgres_data:
    driver: local

networks:
  flight-network:
    driver: bridge
